/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalSafeidCallbackRouteImport } from './routes/professional.safeid.callback'
import { Route as AuthenticatedReceptionPaymentsRouteImport } from './routes/_authenticated/reception.payments'
import { Route as AuthenticatedReceptionPacientesRouteImport } from './routes/_authenticated/reception.pacientes'
import { Route as AuthenticatedReceptionMensagensRouteImport } from './routes/_authenticated/reception.mensagens'
import { Route as AuthenticatedReceptionMarketingRouteImport } from './routes/_authenticated/reception.marketing'
import { Route as AuthenticatedReceptionDashboardRouteImport } from './routes/_authenticated/reception.dashboard'
import { Route as AuthenticatedReceptionAgendaRouteImport } from './routes/_authenticated/reception.agenda'
import { Route as AuthenticatedProfessionalSettingsRouteImport } from './routes/_authenticated/professional.settings'
import { Route as AuthenticatedProfessionalSessionsRouteImport } from './routes/_authenticated/professional.sessions'
import { Route as AuthenticatedProfessionalProntuariosRouteImport } from './routes/_authenticated/professional.prontuarios'
import { Route as AuthenticatedProfessionalProcedimentosRouteImport } from './routes/_authenticated/professional.procedimentos'
import { Route as AuthenticatedProfessionalPrescriptionsRouteImport } from './routes/_authenticated/professional.prescriptions'
import { Route as AuthenticatedProfessionalPatientsRouteImport } from './routes/_authenticated/professional.patients'
import { Route as AuthenticatedProfessionalInventoryRouteImport } from './routes/_authenticated/professional.inventory'
import { Route as AuthenticatedProfessionalFinancialRouteImport } from './routes/_authenticated/professional.financial'
import { Route as AuthenticatedProfessionalDashboardRouteImport } from './routes/_authenticated/professional.dashboard'
import { Route as AuthenticatedProfessionalBudgetsRouteImport } from './routes/_authenticated/professional.budgets'
import { Route as AuthenticatedProfessionalAgendaRouteImport } from './routes/_authenticated/professional.agenda'
import { Route as AuthenticatedFinancialRelatoriosRouteImport } from './routes/_authenticated/financial.relatorios'
import { Route as AuthenticatedFinancialReceivablesRouteImport } from './routes/_authenticated/financial.receivables'
import { Route as AuthenticatedFinancialInventoryRouteImport } from './routes/_authenticated/financial.inventory'
import { Route as AuthenticatedFinancialDashboardRouteImport } from './routes/_authenticated/financial.dashboard'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin.relatorios'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedReceptionPacientesIndexRouteImport } from './routes/_authenticated/reception.pacientes.index'
import { Route as AuthenticatedProfessionalPrescriptionsIndexRouteImport } from './routes/_authenticated/professional.prescriptions.index'
import { Route as AuthenticatedProfessionalPatientsIndexRouteImport } from './routes/_authenticated/professional.patients.index'
import { Route as AuthenticatedProfessionalFinancialIndexRouteImport } from './routes/_authenticated/professional.financial.index'
import { Route as AuthenticatedFinancialInventoryIndexRouteImport } from './routes/_authenticated/financial.inventory.index'
import { Route as AuthenticatedReceptionPacientesIdRouteImport } from './routes/_authenticated/reception.pacientes.$id'
import { Route as AuthenticatedProfessionalPrescriptionsNewRouteImport } from './routes/_authenticated/professional.prescriptions.new'
import { Route as AuthenticatedProfessionalFinancialRelatoriosRouteImport } from './routes/_authenticated/professional.financial.relatorios'
import { Route as AuthenticatedProfessionalFinancialDespesasRouteImport } from './routes/_authenticated/professional.financial.despesas'
import { Route as AuthenticatedProfessionalFinancialCaixaRouteImport } from './routes/_authenticated/professional.financial.caixa'
import { Route as AuthenticatedFinancialInventoryItemsRouteImport } from './routes/_authenticated/financial.inventory.items'
import { Route as AuthenticatedFinancialInventoryCategoriesRouteImport } from './routes/_authenticated/financial.inventory.categories'
import { Route as AuthenticatedProfessionalPatientsIdIndexRouteImport } from './routes/_authenticated/professional.patients.$id.index'
import { Route as AuthenticatedFinancialInventoryItemsIndexRouteImport } from './routes/_authenticated/financial.inventory.items.index'
import { Route as AuthenticatedProfessionalPatientsIdRecordRouteImport } from './routes/_authenticated/professional.patients.$id.record'
import { Route as AuthenticatedProfessionalPatientsIdNewEvolutionRouteImport } from './routes/_authenticated/professional.patients.$id.new-evolution'
import { Route as AuthenticatedFinancialInventoryItemsIdRouteImport } from './routes/_authenticated/financial.inventory.items.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalSafeidCallbackRoute =
  ProfessionalSafeidCallbackRouteImport.update({
    id: '/professional/safeid/callback',
    path: '/professional/safeid/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReceptionPaymentsRoute =
  AuthenticatedReceptionPaymentsRouteImport.update({
    id: '/reception/payments',
    path: '/reception/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceptionPacientesRoute =
  AuthenticatedReceptionPacientesRouteImport.update({
    id: '/reception/pacientes',
    path: '/reception/pacientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceptionMensagensRoute =
  AuthenticatedReceptionMensagensRouteImport.update({
    id: '/reception/mensagens',
    path: '/reception/mensagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceptionMarketingRoute =
  AuthenticatedReceptionMarketingRouteImport.update({
    id: '/reception/marketing',
    path: '/reception/marketing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceptionDashboardRoute =
  AuthenticatedReceptionDashboardRouteImport.update({
    id: '/reception/dashboard',
    path: '/reception/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceptionAgendaRoute =
  AuthenticatedReceptionAgendaRouteImport.update({
    id: '/reception/agenda',
    path: '/reception/agenda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalSettingsRoute =
  AuthenticatedProfessionalSettingsRouteImport.update({
    id: '/professional/settings',
    path: '/professional/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalSessionsRoute =
  AuthenticatedProfessionalSessionsRouteImport.update({
    id: '/professional/sessions',
    path: '/professional/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalProntuariosRoute =
  AuthenticatedProfessionalProntuariosRouteImport.update({
    id: '/professional/prontuarios',
    path: '/professional/prontuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalProcedimentosRoute =
  AuthenticatedProfessionalProcedimentosRouteImport.update({
    id: '/professional/procedimentos',
    path: '/professional/procedimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalPrescriptionsRoute =
  AuthenticatedProfessionalPrescriptionsRouteImport.update({
    id: '/professional/prescriptions',
    path: '/professional/prescriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalPatientsRoute =
  AuthenticatedProfessionalPatientsRouteImport.update({
    id: '/professional/patients',
    path: '/professional/patients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalInventoryRoute =
  AuthenticatedProfessionalInventoryRouteImport.update({
    id: '/professional/inventory',
    path: '/professional/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalFinancialRoute =
  AuthenticatedProfessionalFinancialRouteImport.update({
    id: '/professional/financial',
    path: '/professional/financial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalDashboardRoute =
  AuthenticatedProfessionalDashboardRouteImport.update({
    id: '/professional/dashboard',
    path: '/professional/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalBudgetsRoute =
  AuthenticatedProfessionalBudgetsRouteImport.update({
    id: '/professional/budgets',
    path: '/professional/budgets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionalAgendaRoute =
  AuthenticatedProfessionalAgendaRouteImport.update({
    id: '/professional/agenda',
    path: '/professional/agenda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancialRelatoriosRoute =
  AuthenticatedFinancialRelatoriosRouteImport.update({
    id: '/financial/relatorios',
    path: '/financial/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancialReceivablesRoute =
  AuthenticatedFinancialReceivablesRouteImport.update({
    id: '/financial/receivables',
    path: '/financial/receivables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancialInventoryRoute =
  AuthenticatedFinancialInventoryRouteImport.update({
    id: '/financial/inventory',
    path: '/financial/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancialDashboardRoute =
  AuthenticatedFinancialDashboardRouteImport.update({
    id: '/financial/dashboard',
    path: '/financial/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/admin/relatorios',
    path: '/admin/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceptionPacientesIndexRoute =
  AuthenticatedReceptionPacientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReceptionPacientesRoute,
  } as any)
const AuthenticatedProfessionalPrescriptionsIndexRoute =
  AuthenticatedProfessionalPrescriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfessionalPrescriptionsRoute,
  } as any)
const AuthenticatedProfessionalPatientsIndexRoute =
  AuthenticatedProfessionalPatientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfessionalPatientsRoute,
  } as any)
const AuthenticatedProfessionalFinancialIndexRoute =
  AuthenticatedProfessionalFinancialIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfessionalFinancialRoute,
  } as any)
const AuthenticatedFinancialInventoryIndexRoute =
  AuthenticatedFinancialInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinancialInventoryRoute,
  } as any)
const AuthenticatedReceptionPacientesIdRoute =
  AuthenticatedReceptionPacientesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedReceptionPacientesRoute,
  } as any)
const AuthenticatedProfessionalPrescriptionsNewRoute =
  AuthenticatedProfessionalPrescriptionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProfessionalPrescriptionsRoute,
  } as any)
const AuthenticatedProfessionalFinancialRelatoriosRoute =
  AuthenticatedProfessionalFinancialRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedProfessionalFinancialRoute,
  } as any)
const AuthenticatedProfessionalFinancialDespesasRoute =
  AuthenticatedProfessionalFinancialDespesasRouteImport.update({
    id: '/despesas',
    path: '/despesas',
    getParentRoute: () => AuthenticatedProfessionalFinancialRoute,
  } as any)
const AuthenticatedProfessionalFinancialCaixaRoute =
  AuthenticatedProfessionalFinancialCaixaRouteImport.update({
    id: '/caixa',
    path: '/caixa',
    getParentRoute: () => AuthenticatedProfessionalFinancialRoute,
  } as any)
const AuthenticatedFinancialInventoryItemsRoute =
  AuthenticatedFinancialInventoryItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => AuthenticatedFinancialInventoryRoute,
  } as any)
const AuthenticatedFinancialInventoryCategoriesRoute =
  AuthenticatedFinancialInventoryCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedFinancialInventoryRoute,
  } as any)
const AuthenticatedProfessionalPatientsIdIndexRoute =
  AuthenticatedProfessionalPatientsIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedProfessionalPatientsRoute,
  } as any)
const AuthenticatedFinancialInventoryItemsIndexRoute =
  AuthenticatedFinancialInventoryItemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinancialInventoryItemsRoute,
  } as any)
const AuthenticatedProfessionalPatientsIdRecordRoute =
  AuthenticatedProfessionalPatientsIdRecordRouteImport.update({
    id: '/$id/record',
    path: '/$id/record',
    getParentRoute: () => AuthenticatedProfessionalPatientsRoute,
  } as any)
const AuthenticatedProfessionalPatientsIdNewEvolutionRoute =
  AuthenticatedProfessionalPatientsIdNewEvolutionRouteImport.update({
    id: '/$id/new-evolution',
    path: '/$id/new-evolution',
    getParentRoute: () => AuthenticatedProfessionalPatientsRoute,
  } as any)
const AuthenticatedFinancialInventoryItemsIdRoute =
  AuthenticatedFinancialInventoryItemsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFinancialInventoryItemsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/financial/dashboard': typeof AuthenticatedFinancialDashboardRoute
  '/financial/inventory': typeof AuthenticatedFinancialInventoryRouteWithChildren
  '/financial/receivables': typeof AuthenticatedFinancialReceivablesRoute
  '/financial/relatorios': typeof AuthenticatedFinancialRelatoriosRoute
  '/professional/agenda': typeof AuthenticatedProfessionalAgendaRoute
  '/professional/budgets': typeof AuthenticatedProfessionalBudgetsRoute
  '/professional/dashboard': typeof AuthenticatedProfessionalDashboardRoute
  '/professional/financial': typeof AuthenticatedProfessionalFinancialRouteWithChildren
  '/professional/inventory': typeof AuthenticatedProfessionalInventoryRoute
  '/professional/patients': typeof AuthenticatedProfessionalPatientsRouteWithChildren
  '/professional/prescriptions': typeof AuthenticatedProfessionalPrescriptionsRouteWithChildren
  '/professional/procedimentos': typeof AuthenticatedProfessionalProcedimentosRoute
  '/professional/prontuarios': typeof AuthenticatedProfessionalProntuariosRoute
  '/professional/sessions': typeof AuthenticatedProfessionalSessionsRoute
  '/professional/settings': typeof AuthenticatedProfessionalSettingsRoute
  '/reception/agenda': typeof AuthenticatedReceptionAgendaRoute
  '/reception/dashboard': typeof AuthenticatedReceptionDashboardRoute
  '/reception/marketing': typeof AuthenticatedReceptionMarketingRoute
  '/reception/mensagens': typeof AuthenticatedReceptionMensagensRoute
  '/reception/pacientes': typeof AuthenticatedReceptionPacientesRouteWithChildren
  '/reception/payments': typeof AuthenticatedReceptionPaymentsRoute
  '/professional/safeid/callback': typeof ProfessionalSafeidCallbackRoute
  '/financial/inventory/categories': typeof AuthenticatedFinancialInventoryCategoriesRoute
  '/financial/inventory/items': typeof AuthenticatedFinancialInventoryItemsRouteWithChildren
  '/professional/financial/caixa': typeof AuthenticatedProfessionalFinancialCaixaRoute
  '/professional/financial/despesas': typeof AuthenticatedProfessionalFinancialDespesasRoute
  '/professional/financial/relatorios': typeof AuthenticatedProfessionalFinancialRelatoriosRoute
  '/professional/prescriptions/new': typeof AuthenticatedProfessionalPrescriptionsNewRoute
  '/reception/pacientes/$id': typeof AuthenticatedReceptionPacientesIdRoute
  '/financial/inventory/': typeof AuthenticatedFinancialInventoryIndexRoute
  '/professional/financial/': typeof AuthenticatedProfessionalFinancialIndexRoute
  '/professional/patients/': typeof AuthenticatedProfessionalPatientsIndexRoute
  '/professional/prescriptions/': typeof AuthenticatedProfessionalPrescriptionsIndexRoute
  '/reception/pacientes/': typeof AuthenticatedReceptionPacientesIndexRoute
  '/financial/inventory/items/$id': typeof AuthenticatedFinancialInventoryItemsIdRoute
  '/professional/patients/$id/new-evolution': typeof AuthenticatedProfessionalPatientsIdNewEvolutionRoute
  '/professional/patients/$id/record': typeof AuthenticatedProfessionalPatientsIdRecordRoute
  '/financial/inventory/items/': typeof AuthenticatedFinancialInventoryItemsIndexRoute
  '/professional/patients/$id/': typeof AuthenticatedProfessionalPatientsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/financial/dashboard': typeof AuthenticatedFinancialDashboardRoute
  '/financial/receivables': typeof AuthenticatedFinancialReceivablesRoute
  '/financial/relatorios': typeof AuthenticatedFinancialRelatoriosRoute
  '/professional/agenda': typeof AuthenticatedProfessionalAgendaRoute
  '/professional/budgets': typeof AuthenticatedProfessionalBudgetsRoute
  '/professional/dashboard': typeof AuthenticatedProfessionalDashboardRoute
  '/professional/inventory': typeof AuthenticatedProfessionalInventoryRoute
  '/professional/procedimentos': typeof AuthenticatedProfessionalProcedimentosRoute
  '/professional/prontuarios': typeof AuthenticatedProfessionalProntuariosRoute
  '/professional/sessions': typeof AuthenticatedProfessionalSessionsRoute
  '/professional/settings': typeof AuthenticatedProfessionalSettingsRoute
  '/reception/agenda': typeof AuthenticatedReceptionAgendaRoute
  '/reception/dashboard': typeof AuthenticatedReceptionDashboardRoute
  '/reception/marketing': typeof AuthenticatedReceptionMarketingRoute
  '/reception/mensagens': typeof AuthenticatedReceptionMensagensRoute
  '/reception/payments': typeof AuthenticatedReceptionPaymentsRoute
  '/professional/safeid/callback': typeof ProfessionalSafeidCallbackRoute
  '/financial/inventory/categories': typeof AuthenticatedFinancialInventoryCategoriesRoute
  '/professional/financial/caixa': typeof AuthenticatedProfessionalFinancialCaixaRoute
  '/professional/financial/despesas': typeof AuthenticatedProfessionalFinancialDespesasRoute
  '/professional/financial/relatorios': typeof AuthenticatedProfessionalFinancialRelatoriosRoute
  '/professional/prescriptions/new': typeof AuthenticatedProfessionalPrescriptionsNewRoute
  '/reception/pacientes/$id': typeof AuthenticatedReceptionPacientesIdRoute
  '/financial/inventory': typeof AuthenticatedFinancialInventoryIndexRoute
  '/professional/financial': typeof AuthenticatedProfessionalFinancialIndexRoute
  '/professional/patients': typeof AuthenticatedProfessionalPatientsIndexRoute
  '/professional/prescriptions': typeof AuthenticatedProfessionalPrescriptionsIndexRoute
  '/reception/pacientes': typeof AuthenticatedReceptionPacientesIndexRoute
  '/financial/inventory/items/$id': typeof AuthenticatedFinancialInventoryItemsIdRoute
  '/professional/patients/$id/new-evolution': typeof AuthenticatedProfessionalPatientsIdNewEvolutionRoute
  '/professional/patients/$id/record': typeof AuthenticatedProfessionalPatientsIdRecordRoute
  '/financial/inventory/items': typeof AuthenticatedFinancialInventoryItemsIndexRoute
  '/professional/patients/$id': typeof AuthenticatedProfessionalPatientsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/financial/dashboard': typeof AuthenticatedFinancialDashboardRoute
  '/_authenticated/financial/inventory': typeof AuthenticatedFinancialInventoryRouteWithChildren
  '/_authenticated/financial/receivables': typeof AuthenticatedFinancialReceivablesRoute
  '/_authenticated/financial/relatorios': typeof AuthenticatedFinancialRelatoriosRoute
  '/_authenticated/professional/agenda': typeof AuthenticatedProfessionalAgendaRoute
  '/_authenticated/professional/budgets': typeof AuthenticatedProfessionalBudgetsRoute
  '/_authenticated/professional/dashboard': typeof AuthenticatedProfessionalDashboardRoute
  '/_authenticated/professional/financial': typeof AuthenticatedProfessionalFinancialRouteWithChildren
  '/_authenticated/professional/inventory': typeof AuthenticatedProfessionalInventoryRoute
  '/_authenticated/professional/patients': typeof AuthenticatedProfessionalPatientsRouteWithChildren
  '/_authenticated/professional/prescriptions': typeof AuthenticatedProfessionalPrescriptionsRouteWithChildren
  '/_authenticated/professional/procedimentos': typeof AuthenticatedProfessionalProcedimentosRoute
  '/_authenticated/professional/prontuarios': typeof AuthenticatedProfessionalProntuariosRoute
  '/_authenticated/professional/sessions': typeof AuthenticatedProfessionalSessionsRoute
  '/_authenticated/professional/settings': typeof AuthenticatedProfessionalSettingsRoute
  '/_authenticated/reception/agenda': typeof AuthenticatedReceptionAgendaRoute
  '/_authenticated/reception/dashboard': typeof AuthenticatedReceptionDashboardRoute
  '/_authenticated/reception/marketing': typeof AuthenticatedReceptionMarketingRoute
  '/_authenticated/reception/mensagens': typeof AuthenticatedReceptionMensagensRoute
  '/_authenticated/reception/pacientes': typeof AuthenticatedReceptionPacientesRouteWithChildren
  '/_authenticated/reception/payments': typeof AuthenticatedReceptionPaymentsRoute
  '/professional/safeid/callback': typeof ProfessionalSafeidCallbackRoute
  '/_authenticated/financial/inventory/categories': typeof AuthenticatedFinancialInventoryCategoriesRoute
  '/_authenticated/financial/inventory/items': typeof AuthenticatedFinancialInventoryItemsRouteWithChildren
  '/_authenticated/professional/financial/caixa': typeof AuthenticatedProfessionalFinancialCaixaRoute
  '/_authenticated/professional/financial/despesas': typeof AuthenticatedProfessionalFinancialDespesasRoute
  '/_authenticated/professional/financial/relatorios': typeof AuthenticatedProfessionalFinancialRelatoriosRoute
  '/_authenticated/professional/prescriptions/new': typeof AuthenticatedProfessionalPrescriptionsNewRoute
  '/_authenticated/reception/pacientes/$id': typeof AuthenticatedReceptionPacientesIdRoute
  '/_authenticated/financial/inventory/': typeof AuthenticatedFinancialInventoryIndexRoute
  '/_authenticated/professional/financial/': typeof AuthenticatedProfessionalFinancialIndexRoute
  '/_authenticated/professional/patients/': typeof AuthenticatedProfessionalPatientsIndexRoute
  '/_authenticated/professional/prescriptions/': typeof AuthenticatedProfessionalPrescriptionsIndexRoute
  '/_authenticated/reception/pacientes/': typeof AuthenticatedReceptionPacientesIndexRoute
  '/_authenticated/financial/inventory/items/$id': typeof AuthenticatedFinancialInventoryItemsIdRoute
  '/_authenticated/professional/patients/$id/new-evolution': typeof AuthenticatedProfessionalPatientsIdNewEvolutionRoute
  '/_authenticated/professional/patients/$id/record': typeof AuthenticatedProfessionalPatientsIdRecordRoute
  '/_authenticated/financial/inventory/items/': typeof AuthenticatedFinancialInventoryItemsIndexRoute
  '/_authenticated/professional/patients/$id/': typeof AuthenticatedProfessionalPatientsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/dashboard'
    | '/admin/relatorios'
    | '/admin/services'
    | '/admin/settings'
    | '/financial/dashboard'
    | '/financial/inventory'
    | '/financial/receivables'
    | '/financial/relatorios'
    | '/professional/agenda'
    | '/professional/budgets'
    | '/professional/dashboard'
    | '/professional/financial'
    | '/professional/inventory'
    | '/professional/patients'
    | '/professional/prescriptions'
    | '/professional/procedimentos'
    | '/professional/prontuarios'
    | '/professional/sessions'
    | '/professional/settings'
    | '/reception/agenda'
    | '/reception/dashboard'
    | '/reception/marketing'
    | '/reception/mensagens'
    | '/reception/pacientes'
    | '/reception/payments'
    | '/professional/safeid/callback'
    | '/financial/inventory/categories'
    | '/financial/inventory/items'
    | '/professional/financial/caixa'
    | '/professional/financial/despesas'
    | '/professional/financial/relatorios'
    | '/professional/prescriptions/new'
    | '/reception/pacientes/$id'
    | '/financial/inventory/'
    | '/professional/financial/'
    | '/professional/patients/'
    | '/professional/prescriptions/'
    | '/reception/pacientes/'
    | '/financial/inventory/items/$id'
    | '/professional/patients/$id/new-evolution'
    | '/professional/patients/$id/record'
    | '/financial/inventory/items/'
    | '/professional/patients/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/dashboard'
    | '/admin/relatorios'
    | '/admin/services'
    | '/admin/settings'
    | '/financial/dashboard'
    | '/financial/receivables'
    | '/financial/relatorios'
    | '/professional/agenda'
    | '/professional/budgets'
    | '/professional/dashboard'
    | '/professional/inventory'
    | '/professional/procedimentos'
    | '/professional/prontuarios'
    | '/professional/sessions'
    | '/professional/settings'
    | '/reception/agenda'
    | '/reception/dashboard'
    | '/reception/marketing'
    | '/reception/mensagens'
    | '/reception/payments'
    | '/professional/safeid/callback'
    | '/financial/inventory/categories'
    | '/professional/financial/caixa'
    | '/professional/financial/despesas'
    | '/professional/financial/relatorios'
    | '/professional/prescriptions/new'
    | '/reception/pacientes/$id'
    | '/financial/inventory'
    | '/professional/financial'
    | '/professional/patients'
    | '/professional/prescriptions'
    | '/reception/pacientes'
    | '/financial/inventory/items/$id'
    | '/professional/patients/$id/new-evolution'
    | '/professional/patients/$id/record'
    | '/financial/inventory/items'
    | '/professional/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/financial/dashboard'
    | '/_authenticated/financial/inventory'
    | '/_authenticated/financial/receivables'
    | '/_authenticated/financial/relatorios'
    | '/_authenticated/professional/agenda'
    | '/_authenticated/professional/budgets'
    | '/_authenticated/professional/dashboard'
    | '/_authenticated/professional/financial'
    | '/_authenticated/professional/inventory'
    | '/_authenticated/professional/patients'
    | '/_authenticated/professional/prescriptions'
    | '/_authenticated/professional/procedimentos'
    | '/_authenticated/professional/prontuarios'
    | '/_authenticated/professional/sessions'
    | '/_authenticated/professional/settings'
    | '/_authenticated/reception/agenda'
    | '/_authenticated/reception/dashboard'
    | '/_authenticated/reception/marketing'
    | '/_authenticated/reception/mensagens'
    | '/_authenticated/reception/pacientes'
    | '/_authenticated/reception/payments'
    | '/professional/safeid/callback'
    | '/_authenticated/financial/inventory/categories'
    | '/_authenticated/financial/inventory/items'
    | '/_authenticated/professional/financial/caixa'
    | '/_authenticated/professional/financial/despesas'
    | '/_authenticated/professional/financial/relatorios'
    | '/_authenticated/professional/prescriptions/new'
    | '/_authenticated/reception/pacientes/$id'
    | '/_authenticated/financial/inventory/'
    | '/_authenticated/professional/financial/'
    | '/_authenticated/professional/patients/'
    | '/_authenticated/professional/prescriptions/'
    | '/_authenticated/reception/pacientes/'
    | '/_authenticated/financial/inventory/items/$id'
    | '/_authenticated/professional/patients/$id/new-evolution'
    | '/_authenticated/professional/patients/$id/record'
    | '/_authenticated/financial/inventory/items/'
    | '/_authenticated/professional/patients/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfessionalSafeidCallbackRoute: typeof ProfessionalSafeidCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/safeid/callback': {
      id: '/professional/safeid/callback'
      path: '/professional/safeid/callback'
      fullPath: '/professional/safeid/callback'
      preLoaderRoute: typeof ProfessionalSafeidCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reception/payments': {
      id: '/_authenticated/reception/payments'
      path: '/reception/payments'
      fullPath: '/reception/payments'
      preLoaderRoute: typeof AuthenticatedReceptionPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception/pacientes': {
      id: '/_authenticated/reception/pacientes'
      path: '/reception/pacientes'
      fullPath: '/reception/pacientes'
      preLoaderRoute: typeof AuthenticatedReceptionPacientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception/mensagens': {
      id: '/_authenticated/reception/mensagens'
      path: '/reception/mensagens'
      fullPath: '/reception/mensagens'
      preLoaderRoute: typeof AuthenticatedReceptionMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception/marketing': {
      id: '/_authenticated/reception/marketing'
      path: '/reception/marketing'
      fullPath: '/reception/marketing'
      preLoaderRoute: typeof AuthenticatedReceptionMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception/dashboard': {
      id: '/_authenticated/reception/dashboard'
      path: '/reception/dashboard'
      fullPath: '/reception/dashboard'
      preLoaderRoute: typeof AuthenticatedReceptionDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception/agenda': {
      id: '/_authenticated/reception/agenda'
      path: '/reception/agenda'
      fullPath: '/reception/agenda'
      preLoaderRoute: typeof AuthenticatedReceptionAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/settings': {
      id: '/_authenticated/professional/settings'
      path: '/professional/settings'
      fullPath: '/professional/settings'
      preLoaderRoute: typeof AuthenticatedProfessionalSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/sessions': {
      id: '/_authenticated/professional/sessions'
      path: '/professional/sessions'
      fullPath: '/professional/sessions'
      preLoaderRoute: typeof AuthenticatedProfessionalSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/prontuarios': {
      id: '/_authenticated/professional/prontuarios'
      path: '/professional/prontuarios'
      fullPath: '/professional/prontuarios'
      preLoaderRoute: typeof AuthenticatedProfessionalProntuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/procedimentos': {
      id: '/_authenticated/professional/procedimentos'
      path: '/professional/procedimentos'
      fullPath: '/professional/procedimentos'
      preLoaderRoute: typeof AuthenticatedProfessionalProcedimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/prescriptions': {
      id: '/_authenticated/professional/prescriptions'
      path: '/professional/prescriptions'
      fullPath: '/professional/prescriptions'
      preLoaderRoute: typeof AuthenticatedProfessionalPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/patients': {
      id: '/_authenticated/professional/patients'
      path: '/professional/patients'
      fullPath: '/professional/patients'
      preLoaderRoute: typeof AuthenticatedProfessionalPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/inventory': {
      id: '/_authenticated/professional/inventory'
      path: '/professional/inventory'
      fullPath: '/professional/inventory'
      preLoaderRoute: typeof AuthenticatedProfessionalInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/financial': {
      id: '/_authenticated/professional/financial'
      path: '/professional/financial'
      fullPath: '/professional/financial'
      preLoaderRoute: typeof AuthenticatedProfessionalFinancialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/dashboard': {
      id: '/_authenticated/professional/dashboard'
      path: '/professional/dashboard'
      fullPath: '/professional/dashboard'
      preLoaderRoute: typeof AuthenticatedProfessionalDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/budgets': {
      id: '/_authenticated/professional/budgets'
      path: '/professional/budgets'
      fullPath: '/professional/budgets'
      preLoaderRoute: typeof AuthenticatedProfessionalBudgetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professional/agenda': {
      id: '/_authenticated/professional/agenda'
      path: '/professional/agenda'
      fullPath: '/professional/agenda'
      preLoaderRoute: typeof AuthenticatedProfessionalAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial/relatorios': {
      id: '/_authenticated/financial/relatorios'
      path: '/financial/relatorios'
      fullPath: '/financial/relatorios'
      preLoaderRoute: typeof AuthenticatedFinancialRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial/receivables': {
      id: '/_authenticated/financial/receivables'
      path: '/financial/receivables'
      fullPath: '/financial/receivables'
      preLoaderRoute: typeof AuthenticatedFinancialReceivablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial/inventory': {
      id: '/_authenticated/financial/inventory'
      path: '/financial/inventory'
      fullPath: '/financial/inventory'
      preLoaderRoute: typeof AuthenticatedFinancialInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial/dashboard': {
      id: '/_authenticated/financial/dashboard'
      path: '/financial/dashboard'
      fullPath: '/financial/dashboard'
      preLoaderRoute: typeof AuthenticatedFinancialDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reception/pacientes/': {
      id: '/_authenticated/reception/pacientes/'
      path: '/'
      fullPath: '/reception/pacientes/'
      preLoaderRoute: typeof AuthenticatedReceptionPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedReceptionPacientesRoute
    }
    '/_authenticated/professional/prescriptions/': {
      id: '/_authenticated/professional/prescriptions/'
      path: '/'
      fullPath: '/professional/prescriptions/'
      preLoaderRoute: typeof AuthenticatedProfessionalPrescriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedProfessionalPrescriptionsRoute
    }
    '/_authenticated/professional/patients/': {
      id: '/_authenticated/professional/patients/'
      path: '/'
      fullPath: '/professional/patients/'
      preLoaderRoute: typeof AuthenticatedProfessionalPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedProfessionalPatientsRoute
    }
    '/_authenticated/professional/financial/': {
      id: '/_authenticated/professional/financial/'
      path: '/'
      fullPath: '/professional/financial/'
      preLoaderRoute: typeof AuthenticatedProfessionalFinancialIndexRouteImport
      parentRoute: typeof AuthenticatedProfessionalFinancialRoute
    }
    '/_authenticated/financial/inventory/': {
      id: '/_authenticated/financial/inventory/'
      path: '/'
      fullPath: '/financial/inventory/'
      preLoaderRoute: typeof AuthenticatedFinancialInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedFinancialInventoryRoute
    }
    '/_authenticated/reception/pacientes/$id': {
      id: '/_authenticated/reception/pacientes/$id'
      path: '/$id'
      fullPath: '/reception/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedReceptionPacientesIdRouteImport
      parentRoute: typeof AuthenticatedReceptionPacientesRoute
    }
    '/_authenticated/professional/prescriptions/new': {
      id: '/_authenticated/professional/prescriptions/new'
      path: '/new'
      fullPath: '/professional/prescriptions/new'
      preLoaderRoute: typeof AuthenticatedProfessionalPrescriptionsNewRouteImport
      parentRoute: typeof AuthenticatedProfessionalPrescriptionsRoute
    }
    '/_authenticated/professional/financial/relatorios': {
      id: '/_authenticated/professional/financial/relatorios'
      path: '/relatorios'
      fullPath: '/professional/financial/relatorios'
      preLoaderRoute: typeof AuthenticatedProfessionalFinancialRelatoriosRouteImport
      parentRoute: typeof AuthenticatedProfessionalFinancialRoute
    }
    '/_authenticated/professional/financial/despesas': {
      id: '/_authenticated/professional/financial/despesas'
      path: '/despesas'
      fullPath: '/professional/financial/despesas'
      preLoaderRoute: typeof AuthenticatedProfessionalFinancialDespesasRouteImport
      parentRoute: typeof AuthenticatedProfessionalFinancialRoute
    }
    '/_authenticated/professional/financial/caixa': {
      id: '/_authenticated/professional/financial/caixa'
      path: '/caixa'
      fullPath: '/professional/financial/caixa'
      preLoaderRoute: typeof AuthenticatedProfessionalFinancialCaixaRouteImport
      parentRoute: typeof AuthenticatedProfessionalFinancialRoute
    }
    '/_authenticated/financial/inventory/items': {
      id: '/_authenticated/financial/inventory/items'
      path: '/items'
      fullPath: '/financial/inventory/items'
      preLoaderRoute: typeof AuthenticatedFinancialInventoryItemsRouteImport
      parentRoute: typeof AuthenticatedFinancialInventoryRoute
    }
    '/_authenticated/financial/inventory/categories': {
      id: '/_authenticated/financial/inventory/categories'
      path: '/categories'
      fullPath: '/financial/inventory/categories'
      preLoaderRoute: typeof AuthenticatedFinancialInventoryCategoriesRouteImport
      parentRoute: typeof AuthenticatedFinancialInventoryRoute
    }
    '/_authenticated/professional/patients/$id/': {
      id: '/_authenticated/professional/patients/$id/'
      path: '/$id'
      fullPath: '/professional/patients/$id/'
      preLoaderRoute: typeof AuthenticatedProfessionalPatientsIdIndexRouteImport
      parentRoute: typeof AuthenticatedProfessionalPatientsRoute
    }
    '/_authenticated/financial/inventory/items/': {
      id: '/_authenticated/financial/inventory/items/'
      path: '/'
      fullPath: '/financial/inventory/items/'
      preLoaderRoute: typeof AuthenticatedFinancialInventoryItemsIndexRouteImport
      parentRoute: typeof AuthenticatedFinancialInventoryItemsRoute
    }
    '/_authenticated/professional/patients/$id/record': {
      id: '/_authenticated/professional/patients/$id/record'
      path: '/$id/record'
      fullPath: '/professional/patients/$id/record'
      preLoaderRoute: typeof AuthenticatedProfessionalPatientsIdRecordRouteImport
      parentRoute: typeof AuthenticatedProfessionalPatientsRoute
    }
    '/_authenticated/professional/patients/$id/new-evolution': {
      id: '/_authenticated/professional/patients/$id/new-evolution'
      path: '/$id/new-evolution'
      fullPath: '/professional/patients/$id/new-evolution'
      preLoaderRoute: typeof AuthenticatedProfessionalPatientsIdNewEvolutionRouteImport
      parentRoute: typeof AuthenticatedProfessionalPatientsRoute
    }
    '/_authenticated/financial/inventory/items/$id': {
      id: '/_authenticated/financial/inventory/items/$id'
      path: '/$id'
      fullPath: '/financial/inventory/items/$id'
      preLoaderRoute: typeof AuthenticatedFinancialInventoryItemsIdRouteImport
      parentRoute: typeof AuthenticatedFinancialInventoryItemsRoute
    }
  }
}

interface AuthenticatedFinancialInventoryItemsRouteChildren {
  AuthenticatedFinancialInventoryItemsIdRoute: typeof AuthenticatedFinancialInventoryItemsIdRoute
  AuthenticatedFinancialInventoryItemsIndexRoute: typeof AuthenticatedFinancialInventoryItemsIndexRoute
}

const AuthenticatedFinancialInventoryItemsRouteChildren: AuthenticatedFinancialInventoryItemsRouteChildren =
  {
    AuthenticatedFinancialInventoryItemsIdRoute:
      AuthenticatedFinancialInventoryItemsIdRoute,
    AuthenticatedFinancialInventoryItemsIndexRoute:
      AuthenticatedFinancialInventoryItemsIndexRoute,
  }

const AuthenticatedFinancialInventoryItemsRouteWithChildren =
  AuthenticatedFinancialInventoryItemsRoute._addFileChildren(
    AuthenticatedFinancialInventoryItemsRouteChildren,
  )

interface AuthenticatedFinancialInventoryRouteChildren {
  AuthenticatedFinancialInventoryCategoriesRoute: typeof AuthenticatedFinancialInventoryCategoriesRoute
  AuthenticatedFinancialInventoryItemsRoute: typeof AuthenticatedFinancialInventoryItemsRouteWithChildren
  AuthenticatedFinancialInventoryIndexRoute: typeof AuthenticatedFinancialInventoryIndexRoute
}

const AuthenticatedFinancialInventoryRouteChildren: AuthenticatedFinancialInventoryRouteChildren =
  {
    AuthenticatedFinancialInventoryCategoriesRoute:
      AuthenticatedFinancialInventoryCategoriesRoute,
    AuthenticatedFinancialInventoryItemsRoute:
      AuthenticatedFinancialInventoryItemsRouteWithChildren,
    AuthenticatedFinancialInventoryIndexRoute:
      AuthenticatedFinancialInventoryIndexRoute,
  }

const AuthenticatedFinancialInventoryRouteWithChildren =
  AuthenticatedFinancialInventoryRoute._addFileChildren(
    AuthenticatedFinancialInventoryRouteChildren,
  )

interface AuthenticatedProfessionalFinancialRouteChildren {
  AuthenticatedProfessionalFinancialCaixaRoute: typeof AuthenticatedProfessionalFinancialCaixaRoute
  AuthenticatedProfessionalFinancialDespesasRoute: typeof AuthenticatedProfessionalFinancialDespesasRoute
  AuthenticatedProfessionalFinancialRelatoriosRoute: typeof AuthenticatedProfessionalFinancialRelatoriosRoute
  AuthenticatedProfessionalFinancialIndexRoute: typeof AuthenticatedProfessionalFinancialIndexRoute
}

const AuthenticatedProfessionalFinancialRouteChildren: AuthenticatedProfessionalFinancialRouteChildren =
  {
    AuthenticatedProfessionalFinancialCaixaRoute:
      AuthenticatedProfessionalFinancialCaixaRoute,
    AuthenticatedProfessionalFinancialDespesasRoute:
      AuthenticatedProfessionalFinancialDespesasRoute,
    AuthenticatedProfessionalFinancialRelatoriosRoute:
      AuthenticatedProfessionalFinancialRelatoriosRoute,
    AuthenticatedProfessionalFinancialIndexRoute:
      AuthenticatedProfessionalFinancialIndexRoute,
  }

const AuthenticatedProfessionalFinancialRouteWithChildren =
  AuthenticatedProfessionalFinancialRoute._addFileChildren(
    AuthenticatedProfessionalFinancialRouteChildren,
  )

interface AuthenticatedProfessionalPatientsRouteChildren {
  AuthenticatedProfessionalPatientsIndexRoute: typeof AuthenticatedProfessionalPatientsIndexRoute
  AuthenticatedProfessionalPatientsIdNewEvolutionRoute: typeof AuthenticatedProfessionalPatientsIdNewEvolutionRoute
  AuthenticatedProfessionalPatientsIdRecordRoute: typeof AuthenticatedProfessionalPatientsIdRecordRoute
  AuthenticatedProfessionalPatientsIdIndexRoute: typeof AuthenticatedProfessionalPatientsIdIndexRoute
}

const AuthenticatedProfessionalPatientsRouteChildren: AuthenticatedProfessionalPatientsRouteChildren =
  {
    AuthenticatedProfessionalPatientsIndexRoute:
      AuthenticatedProfessionalPatientsIndexRoute,
    AuthenticatedProfessionalPatientsIdNewEvolutionRoute:
      AuthenticatedProfessionalPatientsIdNewEvolutionRoute,
    AuthenticatedProfessionalPatientsIdRecordRoute:
      AuthenticatedProfessionalPatientsIdRecordRoute,
    AuthenticatedProfessionalPatientsIdIndexRoute:
      AuthenticatedProfessionalPatientsIdIndexRoute,
  }

const AuthenticatedProfessionalPatientsRouteWithChildren =
  AuthenticatedProfessionalPatientsRoute._addFileChildren(
    AuthenticatedProfessionalPatientsRouteChildren,
  )

interface AuthenticatedProfessionalPrescriptionsRouteChildren {
  AuthenticatedProfessionalPrescriptionsNewRoute: typeof AuthenticatedProfessionalPrescriptionsNewRoute
  AuthenticatedProfessionalPrescriptionsIndexRoute: typeof AuthenticatedProfessionalPrescriptionsIndexRoute
}

const AuthenticatedProfessionalPrescriptionsRouteChildren: AuthenticatedProfessionalPrescriptionsRouteChildren =
  {
    AuthenticatedProfessionalPrescriptionsNewRoute:
      AuthenticatedProfessionalPrescriptionsNewRoute,
    AuthenticatedProfessionalPrescriptionsIndexRoute:
      AuthenticatedProfessionalPrescriptionsIndexRoute,
  }

const AuthenticatedProfessionalPrescriptionsRouteWithChildren =
  AuthenticatedProfessionalPrescriptionsRoute._addFileChildren(
    AuthenticatedProfessionalPrescriptionsRouteChildren,
  )

interface AuthenticatedReceptionPacientesRouteChildren {
  AuthenticatedReceptionPacientesIdRoute: typeof AuthenticatedReceptionPacientesIdRoute
  AuthenticatedReceptionPacientesIndexRoute: typeof AuthenticatedReceptionPacientesIndexRoute
}

const AuthenticatedReceptionPacientesRouteChildren: AuthenticatedReceptionPacientesRouteChildren =
  {
    AuthenticatedReceptionPacientesIdRoute:
      AuthenticatedReceptionPacientesIdRoute,
    AuthenticatedReceptionPacientesIndexRoute:
      AuthenticatedReceptionPacientesIndexRoute,
  }

const AuthenticatedReceptionPacientesRouteWithChildren =
  AuthenticatedReceptionPacientesRoute._addFileChildren(
    AuthenticatedReceptionPacientesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedFinancialDashboardRoute: typeof AuthenticatedFinancialDashboardRoute
  AuthenticatedFinancialInventoryRoute: typeof AuthenticatedFinancialInventoryRouteWithChildren
  AuthenticatedFinancialReceivablesRoute: typeof AuthenticatedFinancialReceivablesRoute
  AuthenticatedFinancialRelatoriosRoute: typeof AuthenticatedFinancialRelatoriosRoute
  AuthenticatedProfessionalAgendaRoute: typeof AuthenticatedProfessionalAgendaRoute
  AuthenticatedProfessionalBudgetsRoute: typeof AuthenticatedProfessionalBudgetsRoute
  AuthenticatedProfessionalDashboardRoute: typeof AuthenticatedProfessionalDashboardRoute
  AuthenticatedProfessionalFinancialRoute: typeof AuthenticatedProfessionalFinancialRouteWithChildren
  AuthenticatedProfessionalInventoryRoute: typeof AuthenticatedProfessionalInventoryRoute
  AuthenticatedProfessionalPatientsRoute: typeof AuthenticatedProfessionalPatientsRouteWithChildren
  AuthenticatedProfessionalPrescriptionsRoute: typeof AuthenticatedProfessionalPrescriptionsRouteWithChildren
  AuthenticatedProfessionalProcedimentosRoute: typeof AuthenticatedProfessionalProcedimentosRoute
  AuthenticatedProfessionalProntuariosRoute: typeof AuthenticatedProfessionalProntuariosRoute
  AuthenticatedProfessionalSessionsRoute: typeof AuthenticatedProfessionalSessionsRoute
  AuthenticatedProfessionalSettingsRoute: typeof AuthenticatedProfessionalSettingsRoute
  AuthenticatedReceptionAgendaRoute: typeof AuthenticatedReceptionAgendaRoute
  AuthenticatedReceptionDashboardRoute: typeof AuthenticatedReceptionDashboardRoute
  AuthenticatedReceptionMarketingRoute: typeof AuthenticatedReceptionMarketingRoute
  AuthenticatedReceptionMensagensRoute: typeof AuthenticatedReceptionMensagensRoute
  AuthenticatedReceptionPacientesRoute: typeof AuthenticatedReceptionPacientesRouteWithChildren
  AuthenticatedReceptionPaymentsRoute: typeof AuthenticatedReceptionPaymentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedFinancialDashboardRoute: AuthenticatedFinancialDashboardRoute,
  AuthenticatedFinancialInventoryRoute:
    AuthenticatedFinancialInventoryRouteWithChildren,
  AuthenticatedFinancialReceivablesRoute:
    AuthenticatedFinancialReceivablesRoute,
  AuthenticatedFinancialRelatoriosRoute: AuthenticatedFinancialRelatoriosRoute,
  AuthenticatedProfessionalAgendaRoute: AuthenticatedProfessionalAgendaRoute,
  AuthenticatedProfessionalBudgetsRoute: AuthenticatedProfessionalBudgetsRoute,
  AuthenticatedProfessionalDashboardRoute:
    AuthenticatedProfessionalDashboardRoute,
  AuthenticatedProfessionalFinancialRoute:
    AuthenticatedProfessionalFinancialRouteWithChildren,
  AuthenticatedProfessionalInventoryRoute:
    AuthenticatedProfessionalInventoryRoute,
  AuthenticatedProfessionalPatientsRoute:
    AuthenticatedProfessionalPatientsRouteWithChildren,
  AuthenticatedProfessionalPrescriptionsRoute:
    AuthenticatedProfessionalPrescriptionsRouteWithChildren,
  AuthenticatedProfessionalProcedimentosRoute:
    AuthenticatedProfessionalProcedimentosRoute,
  AuthenticatedProfessionalProntuariosRoute:
    AuthenticatedProfessionalProntuariosRoute,
  AuthenticatedProfessionalSessionsRoute:
    AuthenticatedProfessionalSessionsRoute,
  AuthenticatedProfessionalSettingsRoute:
    AuthenticatedProfessionalSettingsRoute,
  AuthenticatedReceptionAgendaRoute: AuthenticatedReceptionAgendaRoute,
  AuthenticatedReceptionDashboardRoute: AuthenticatedReceptionDashboardRoute,
  AuthenticatedReceptionMarketingRoute: AuthenticatedReceptionMarketingRoute,
  AuthenticatedReceptionMensagensRoute: AuthenticatedReceptionMensagensRoute,
  AuthenticatedReceptionPacientesRoute:
    AuthenticatedReceptionPacientesRouteWithChildren,
  AuthenticatedReceptionPaymentsRoute: AuthenticatedReceptionPaymentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfessionalSafeidCallbackRoute: ProfessionalSafeidCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
